### ISSUE TITLE
Sphinx 2.0 で動かない

### ISSUE THREAD

**Issue by usaturn** [sphinxjp/sphinxjp.themes.sphinxjp#1]
sphinx 2.0.0 で sphinxjp theme を指定すると下記のエラーが出ます。
```
>make html
Running Sphinx v2.0.0
loading translations [ja]... done
making output directory... done

Theme error:
no theme named 'sphinxjp' found (missing theme.conf?)
```

対応お願いします！

**Comment by tk0miya** [comment]
https://github.com/sphinxjp/sphinxjp.themes.sphinxjp/commit/f89fc1a77118f281d93742cc417fbb60232635e8 で対応しました。1.0.1 をリリースすれば解決します。

**Comment by tk0miya** [comment]
done
