### ISSUE TITLE
note ディレクティブ、warning ディレクティブの枠線が出ない

### ISSUE THREAD

**Issue by usaturn** [sphinxjp/sphinxjp.themes.sphinxjp#2]
Sphinx 1.8.5 で warning の枠線が出ません

![2019-06-01_18h06_02](https://user-images.githubusercontent.com/1503215/58746347-450ebd00-8498-11e9-92e5-033d80fc6cc9.png)

Sphinx 2.0.1 では note , warning の枠線が出ません
![2019-06-01_18h06_37](https://user-images.githubusercontent.com/1503215/58746352-5657c980-8498-11e9-9505-fe25894805ee.png)

https://sphinx-users.jp/gettingstarted/install_windows.html#sphinx

対応お願いします！

**Comment by tk0miya** [comment]
https://github.com/sphinxjp/sphinxjp.themes.sphinxjp/commit/351c403a1593bb755768b7ddbc2dbae8298d922d

修正しました。
